# Use a base image with 64-bit Linux, such as Ubuntu
FROM ubuntu:latest

# Set working directory
WORKDIR /app

# Install necessary tools: wget for downloading, Java for Spring Boot, and Maven for building the app
RUN apt-get update && apt-get install -y \
    wget \
    openjdk-11-jdk \
    maven

# Download sosicon
RUN wget -O sosicon https://github.com/espena/sosicon/blob/master/bin/cmd/linux64/sosicon?raw=true \
    && chmod +x sosicon

# Copy the Spring Boot application source into the container
# Ensure that your application's source code is in the context directory of the Docker build
COPY . /app

# Compile the Spring Boot application
# This step will run 'mvn clean install' inside the /app directory, building your application
RUN mvn clean install

# Expose the port that your Spring application uses
EXPOSE 8080

# Command to run the compiled application
# Replace 'app-name' with the name of your Spring Boot application's JAR file generated by Maven
CMD ["java", "-jar", "target/spatialcon.jar"]